In [2]:
import numpy as np;

In [3]:
x = np.array([1,2,3]) # Vector
x.ndim, x.shape

(1, (3,))

In [5]:
y = np.array([[1], [2], [3]]) # 3 by 1
y.ndim, y.shape

(2, (3, 1))

In [7]:
A = np.array([[1,1,1], [2,2,2], [3,3,3]]) # 3 by 3
A.ndim, A.shape

(2, (3, 3))

In [8]:
a = np.arange(100) # 0 to n-1
print(a)
b = np.linspace(0, 1, 10)   # start, end, num-points
print(b)
c = np.ones((4, 4))  #(4, 4) is a tuple
print(c)
d = np.eye(4)
print(d)
e = np.diag(np.array([1, 2, 3, 4]))
print(e)
d = np.random.rand(4) # uniform in [0, 1]
print(d)
e = np.random.randn(4) # draw from Gaussian

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[0.92561664 0.95277815 0.03087528 0.8867523 ]


In [9]:
x = np.arange(3).reshape(3,1)
print(x)
xp1 = x + 1
print(xp1)
print(xp1 - x)
y = np.arange(3).reshape(1,3)
print(y)
print(2**y)
A = np.arange(9).reshape(3,3)
print(A)

[[0]
 [1]
 [2]]
[[1]
 [2]
 [3]]
[[1]
 [1]
 [1]]
[[0 1 2]]
[[1 2 4]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
print(A * A) # compare with the next..
print(A.dot(A))
print(A.dot(x)) # scalar product
print(A.dot(y.T)) # scalar product with transpose of y

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
[[ 5]
 [14]
 [23]]
[[ 5]
 [14]
 [23]]


In [13]:
a = np.arange(100) # 0 to n-1
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
# axis lets you control columns vs rows
a = np.array([[1,1], [2,2,], [3,3]])
print(a)
print(a.ndim, a.shape)
print(a.sum(axis=0))
print(a.sum(axis=1))

4950
0
99
49.5
[[1 1]
 [2 2]
 [3 3]]
2 (3, 2)
[6 6]
[2 4 6]


In [14]:
A = np.arange(9).reshape(3,3)
print(A[0])
print(A[0][0])
print(A[1])
print(A[1][2])
print(A[2])
print(A[-1])
print(A[-2])
print(A[2, 0]) # third row, first column

[0 1 2]
0
[3 4 5]
5
[6 7 8]
[6 7 8]
[3 4 5]
6


In [15]:
import pandas as pd
books = pd.Series(['Harry Potter and The Philosophers Stone',
 'Artificial Intelligence: A Modern Approach',])
book_class = pd.Series(['Fiction', 'Non-Fiction'])
authors = pd.Series(['JK Rowling', 'Russel and Norvig'])
# note these numbers may have been made up
sold = pd.Series([120000000, 10000])
book_frame = pd.DataFrame({'Book Title': books, 'Book Classification': book_class,
'Author Name': authors, 'Sales': sold})
book_frame # the output of the last expression in a cell is displayed

Book Title Book Classification  \
0     Harry Potter and The Philosophers Stone             Fiction   
1  Artificial Intelligence: A Modern Approach         Non-Fiction   

         Author Name      Sales  
0         JK Rowling  120000000  
1  Russel and Norvig      10000

In [18]:
# don't worry about the .data extension, it's really just a CSV file.
# this won't work, unless we have the crx.data file in this directory.
# df = pd.read_csv('crx.data', sep=',', header=None)

# the following does the same as above, but instead loading it over the Internet
df = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/credit-screening/crx.data', sep=',', header=None)
# print a summary of the dataframe we loaded.
print(df)
# print the first few rows of the dataframe
print(df.head())
# print the last few rows of the dataframe
print(df.tail())

    0      1       2  3  4   5   6     7  8  9   10 11 12     13   14 15
0    b  30.83   0.000  u  g   w   v  1.25  t  t   1  f  g  00202    0  +
1    a  58.67   4.460  u  g   q   h  3.04  t  t   6  f  g  00043  560  +
2    a  24.50   0.500  u  g   q   h  1.50  t  f   0  f  g  00280  824  +
3    b  27.83   1.540  u  g   w   v  3.75  t  t   5  t  g  00100    3  +
4    b  20.17   5.625  u  g   w   v  1.71  t  f   0  f  s  00120    0  +
..  ..    ...     ... .. ..  ..  ..   ... .. ..  .. .. ..    ...  ... ..
685  b  21.08  10.085  y  p   e   h  1.25  f  f   0  f  g  00260    0  -
686  a  22.67   0.750  u  g   c   v  2.00  f  t   2  t  g  00200  394  -
687  a  25.25  13.500  y  p  ff  ff  2.00  f  t   1  t  g  00200    1  -
688  b  17.92   0.205  u  g  aa   v  0.04  f  f   0  f  g  00280  750  -
689  b  35.00   3.375  u  g   c   h  8.29  f  f   0  t  g  00000    0  -

[690 rows x 16 columns]
  0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v 

In [19]:
print(book_frame['Book Title'])
print(book_frame['Book Title'][1])
print(book_frame['Book Title'][0:2])

0       Harry Potter and The Philosophers Stone
1    Artificial Intelligence: A Modern Approach
Name: Book Title, dtype: object
Artificial Intelligence: A Modern Approach
0       Harry Potter and The Philosophers Stone
1    Artificial Intelligence: A Modern Approach
Name: Book Title, dtype: object


In [20]:
print(book_frame.iloc[0])
print(book_frame.iloc[1]['Book Title'])
print(book_frame.iloc[0:1])

Book Title             Harry Potter and The Philosophers Stone
Book Classification                                    Fiction
Author Name                                         JK Rowling
Sales                                                120000000
Name: 0, dtype: object
Artificial Intelligence: A Modern Approach
                                Book Title Book Classification Author Name  \
0  Harry Potter and The Philosophers Stone             Fiction  JK Rowling   

       Sales  
0  120000000  


In [27]:
# Oops, maybe we underestimated the sales of books by a factor of 10
book_frame['Sales'] = book_frame['Sales'] * 10
print(book_frame)
import numpy as np
log_sales = np.log(book_frame['Sales'])
print(log_sales)
book_frame['Log_Sales'] = log_sales
print(book_frame)

                                   Book Title Book Classification  \
0     Harry Potter and The Philosophers Stone             Fiction   
1  Artificial Intelligence: A Modern Approach         Non-Fiction   

         Author Name       Sales  
0         JK Rowling  1200000000  
1  Russel and Norvig      100000  
0    20.905587
1    11.512925
Name: Sales, dtype: float64
                                   Book Title Book Classification  \
0     Harry Potter and The Philosophers Stone             Fiction   
1  Artificial Intelligence: A Modern Approach         Non-Fiction   

         Author Name       Sales  Log_Sales  
0         JK Rowling  1200000000  20.905587  
1  Russel and Norvig      100000  11.512925  


In [32]:
book_frame.iloc[:,:2]

Book Title Book Classification
0     Harry Potter and The Philosophers Stone             Fiction
1  Artificial Intelligence: A Modern Approach         Non-Fiction